language: python
dist: xenial
sudo: true
python:
  - "3.5"
  - "3.6"
  - "3.7"
before_script:
  - cd project
install: "pip install -r project/requirements.txt"
script:
  - flake8 --config ../.flake8
  - python -m unittest discover .